services:
  - name: app
    build:
      dockerfile: Dockerfile
      context: .
    start_command: npm run start
    env:
      - key: MONGODB_URL
        value: mongodb://mongo:27017/myapp
      - key: PORT
        value: "5000"
    health_check:
      http_endpoint: http://localhost:5000/health
      timeout: 10s
      interval: 1m
    dependencies:
      - name: mongo
        resource_type: "small"
  - name: mongo
    image: mongo:4.4